
name: Trigger Integration Tests

on:
  issue_comment:
    types: [created]

jobs:
  build:
    name: Trigger Integration Tests

    runs-on: ubuntu-latest
    if: github.event.comment.body == '/it' && (github.event.comment.author_association == 'COLLABORATOR' || github.event.comment.author_association == 'OWNER')

    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: get pull request url
        id: pullrequest
        run: echo "::set-output name=pullrequest::$(curl ${{ github.event.comment.issue_url }} | jq '.pull_request.url' | sed 's/\"//g')"
      - name: get branch name
        id: branchname
        run: echo "::set-output name=branchname::$(curl ${{ steps.pullrequest.outputs.pullrequest }} | jq '.head.ref' | sed 's/\"//g')"
      - name: get repository
        id: repository
        run: echo "::set-output name=repository::$(curl ${{ steps.pullrequest.outputs.pullrequest }} | jq '.head.repo.full_name' | sed 's/\"//g')"
      - name: checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ steps.repository.outputs.repository }}
          ref: ${{ steps.branchname.outputs.branchname }}
      - name: run consumer tests
        run: cd consumer-test && groovy consumerTestController.groovy
